#!/usr/bin/env python3
"""
Slice a 2-row × 3-col sprite-sheet generated by ChatGPT Image into 6
per-frame PNGs, then assemble a horizontal sheet-transparent.png + an
animation.gif preview.

Usage:
    python3 slice.py source-sheet.png

Inputs:
    source-sheet.png — the raw 2x3 grid from ChatGPT (any size; aspect
    ratio is the only constraint — should be ~1.5:1 for the typical
    1500x1000 ChatGPT output).

Outputs (in this folder):
    frame_1.png … frame_6.png  — individual frames, transparent bg
    sheet-transparent.png      — horizontal 1x6 sheet for in-game atlas
    animation.gif              — 12fps preview for the catalog page

Frame ordering: row-major (top-left → top-right → bottom-left → …),
matching the master prompt's FRAME_1 .. FRAME_6 left-to-right /
top-to-bottom.

Background-to-transparency: ChatGPT outputs the character on a black
canvas. The slicer threshold-keys near-black to alpha 0; everything
above the threshold keeps its original RGB + full alpha. Threshold is
tuned for the reference Wefty palette (purple yarn-ball outline + cream
fill); tweak BG_THRESHOLD if your generation has a different background.
"""
import sys
import os
from pathlib import Path
from PIL import Image

# Pixels darker than this in all 3 channels are treated as background.
# Tuned for ChatGPT's solid-black canvas around the character.
BG_THRESHOLD = 24

# How many ms each frame lasts in the preview GIF (12fps ≈ 83ms).
GIF_FRAME_MS = 83


def threshold_to_alpha(img: Image.Image) -> Image.Image:
    """Return a copy of img with near-black pixels keyed to alpha 0."""
    img = img.convert("RGBA")
    px = img.load()
    w, h = img.size
    for y in range(h):
        for x in range(w):
            r, g, b, _ = px[x, y]
            if r < BG_THRESHOLD and g < BG_THRESHOLD and b < BG_THRESHOLD:
                px[x, y] = (0, 0, 0, 0)
    return img


def main():
    if len(sys.argv) < 2:
        print("usage: python3 slice.py <source-sheet.png>")
        sys.exit(2)
    src_path = Path(sys.argv[1])
    if not src_path.exists():
        print(f"error: {src_path} not found")
        sys.exit(2)

    here = Path(__file__).parent.resolve()
    img = Image.open(src_path).convert("RGBA")
    sw, sh = img.size

    # 2 rows × 3 cols layout.
    cols, rows = 3, 2
    cell_w, cell_h = sw // cols, sh // rows

    frames = []
    for i in range(rows * cols):
        row = i // cols
        col = i % cols
        box = (col * cell_w, row * cell_h,
               (col + 1) * cell_w, (row + 1) * cell_h)
        cell = img.crop(box)
        cell = threshold_to_alpha(cell)
        frame_path = here / f"frame_{i+1}.png"
        cell.save(frame_path)
        frames.append(cell)
        print(f"wrote {frame_path.name}  {cell.size}")

    # Horizontal sheet — 1 row × 6 cols, square cells.
    sheet_h = cell_h
    sheet_w = cell_w * len(frames)
    sheet = Image.new("RGBA", (sheet_w, sheet_h), (0, 0, 0, 0))
    for i, f in enumerate(frames):
        sheet.paste(f, (i * cell_w, 0), f)
    sheet_path = here / "sheet-transparent.png"
    sheet.save(sheet_path)
    print(f"wrote {sheet_path.name}  {sheet.size}")

    # Preview GIF — pad onto a same-size canvas so transparency
    # propagates cleanly through GIF's 1-bit alpha.
    gif_path = here / "animation.gif"
    # GIF transparency is finicky; quantize each frame to a palette that
    # reserves index 0 for transparency.
    gif_frames = []
    for f in frames:
        # Drop alpha to 1-bit by alpha-thresholding at 128.
        px = f.load()
        out = Image.new("RGBA", f.size, (0, 0, 0, 0))
        op = out.load()
        for y in range(f.size[1]):
            for x in range(f.size[0]):
                r, g, b, a = px[x, y]
                if a >= 128:
                    op[x, y] = (r, g, b, 255)
                else:
                    op[x, y] = (0, 0, 0, 0)
        gif_frames.append(out)
    gif_frames[0].save(
        gif_path,
        save_all=True,
        append_images=gif_frames[1:],
        duration=GIF_FRAME_MS,
        loop=0,
        disposal=2,
        transparency=0,
    )
    print(f"wrote {gif_path.name}  ({len(gif_frames)} frames @ {GIF_FRAME_MS}ms)")


if __name__ == "__main__":
    main()
