#!/usr/bin/env python3
"""
Slice a 2-row × 3-col sprite-sheet generated by ChatGPT Image into 6
per-frame PNGs, then assemble a horizontal sheet-transparent.png + an
animation.gif preview.

Usage:
    python3 slice.py source-sheet.png

Inputs:
    source-sheet.png — the raw 2x3 grid from ChatGPT (any size; aspect
    ratio is the only constraint — should be ~1.5:1 for the typical
    1500x1000 ChatGPT output).

Outputs (in this folder):
    frame_1.png … frame_6.png  — individual frames, transparent bg
    sheet-transparent.png      — horizontal 1x6 sheet for in-game atlas
    animation.gif              — 12fps preview for the catalog page

Frame ordering: row-major (top-left → top-right → bottom-left → …),
matching the master prompt's FRAME_1 .. FRAME_6 left-to-right /
top-to-bottom.

Background-to-transparency: ChatGPT outputs the character on a black
canvas. The slicer threshold-keys near-black to alpha 0; everything
above the threshold keeps its original RGB + full alpha. Threshold is
tuned for the reference Wefty palette (purple yarn-ball outline + cream
fill); tweak BG_THRESHOLD if your generation has a different background.
"""
import sys
import os
from pathlib import Path
from PIL import Image

# Pixels darker than this in all 3 channels are treated as background.
# Tuned for ChatGPT's solid-black canvas around the character.
BG_THRESHOLD = 24

# How many ms each frame lasts in the preview GIF (12fps ≈ 83ms).
GIF_FRAME_MS = 83


def threshold_to_alpha(img: Image.Image) -> Image.Image:
    """Return a copy of img with near-black pixels keyed to alpha 0."""
    img = img.convert("RGBA")
    px = img.load()
    w, h = img.size
    for y in range(h):
        for x in range(w):
            r, g, b, _ = px[x, y]
            if r < BG_THRESHOLD and g < BG_THRESHOLD and b < BG_THRESHOLD:
                px[x, y] = (0, 0, 0, 0)
    return img


def main():
    if len(sys.argv) < 2:
        print("usage: python3 slice.py <source-sheet.png>")
        sys.exit(2)
    src_path = Path(sys.argv[1])
    if not src_path.exists():
        print(f"error: {src_path} not found")
        sys.exit(2)

    here = Path(__file__).parent.resolve()
    img = Image.open(src_path).convert("RGBA")
    sw, sh = img.size

    # 2 rows × 3 cols layout.
    cols, rows = 3, 2
    cell_w, cell_h = sw // cols, sh // rows

    frames = []
    for i in range(rows * cols):
        row = i // cols
        col = i % cols
        box = (col * cell_w, row * cell_h,
               (col + 1) * cell_w, (row + 1) * cell_h)
        cell = img.crop(box)
        cell = threshold_to_alpha(cell)
        frame_path = here / f"frame_{i+1}.png"
        cell.save(frame_path)
        frames.append(cell)
        print(f"wrote {frame_path.name}  {cell.size}")

    # Horizontal sheet — 1 row × 6 cols, square cells.
    sheet_h = cell_h
    sheet_w = cell_w * len(frames)
    sheet = Image.new("RGBA", (sheet_w, sheet_h), (0, 0, 0, 0))
    for i, f in enumerate(frames):
        sheet.paste(f, (i * cell_w, 0), f)
    sheet_path = here / "sheet-transparent.png"
    sheet.save(sheet_path)
    print(f"wrote {sheet_path.name}  {sheet.size}")

    # Preview GIF — uniform GIF_FRAME_MS per frame. GIF transparency
    # requires the transparent palette index to actually map to "ignore
    # this pixel" — Pillow's auto-quantize doesn't guarantee that
    # (it'll happily mark some random palette index as transparent and
    # corrupt the render). Reliable recipe:
    #   1. Threshold each frame's alpha to 1-bit.
    #   2. Composite onto a sentinel-color RGB so the formerly-
    #      transparent pixels now ARE that color.
    #   3. Build a palette where index 0 is the sentinel + indices
    #      1..255 are an adaptive palette of the actual frame colors.
    #   4. Quantize each frame against that fixed palette.
    #   5. Save with transparency=0. Renderers see "index 0 = ignore"
    #      and skip those pixels cleanly.
    SENTINEL = (255, 0, 255)  # magenta; outside Wefty palette
    gif_frames = []
    for f in frames:
        rgba = f.convert("RGBA")
        alpha = rgba.split()[3].point(lambda a: 255 if a >= 128 else 0)
        bg = Image.new("RGB", rgba.size, SENTINEL)
        bg.paste(rgba, mask=alpha)
        adaptive = bg.quantize(colors=255, method=Image.Quantize.MEDIANCUT)
        adaptive_palette = adaptive.getpalette()[:255 * 3]
        final_palette = list(SENTINEL) + adaptive_palette
        final_pal_img = Image.new("P", (1, 1))
        final_pal_img.putpalette(final_palette)
        p_final = bg.quantize(palette=final_pal_img, dither=Image.Dither.NONE)
        gif_frames.append(p_final)

    gif_path = here / "animation.gif"
    gif_frames[0].save(
        gif_path,
        save_all=True,
        append_images=gif_frames[1:],
        duration=GIF_FRAME_MS,
        loop=0,
        disposal=2,
        transparency=0,
        optimize=False,
    )
    print(f"wrote {gif_path.name}  ({len(gif_frames)} frames @ {GIF_FRAME_MS}ms)")


if __name__ == "__main__":
    main()
