#!/usr/bin/env python3
"""
Slice a 2-row x 3-col sprite-sheet generated by ChatGPT Image into 6
per-frame PNGs, assemble a horizontal sheet-transparent.png, and bake
an animation.gif with PER-FRAME durations read from
pipeline-meta.json's frame_durations_ms array.

Why this differs from wefty-fall/slice.py: the spin-hit cycle has
intentionally non-uniform timing (snappy 40ms at impact, longer at
anticipation/recovery). A single fps doesn't capture that, so we
honor the per-frame durations baked into the meta file.

Usage:
    python3 slice.py source-sheet.png

Inputs:
    source-sheet.png — raw 2x3 grid from ChatGPT.
    pipeline-meta.json — must contain frame_durations_ms: [...] with
        len == frame_count (6 here).

Outputs:
    frame_1.png .. frame_6.png — individual frames, transparent bg.
    sheet-transparent.png      — horizontal 1x6 sheet for in-game atlas.
    animation.gif              — 6 frames with per-panel durations.
"""
import sys
import json
from pathlib import Path
from PIL import Image

# Pixels darker than this in all 3 channels are treated as background.
# Tuned for ChatGPT's solid-black canvas around the character.
BG_THRESHOLD = 24


def threshold_to_alpha(img: Image.Image) -> Image.Image:
    """Return a copy of img with near-black pixels keyed to alpha 0."""
    img = img.convert("RGBA")
    px = img.load()
    w, h = img.size
    for y in range(h):
        for x in range(w):
            r, g, b, _ = px[x, y]
            if r < BG_THRESHOLD and g < BG_THRESHOLD and b < BG_THRESHOLD:
                px[x, y] = (0, 0, 0, 0)
    return img


def main():
    if len(sys.argv) < 2:
        print("usage: python3 slice.py <source-sheet.png>")
        sys.exit(2)
    src_path = Path(sys.argv[1])
    if not src_path.exists():
        print(f"error: {src_path} not found")
        sys.exit(2)

    here = Path(__file__).parent.resolve()
    meta_path = here / "pipeline-meta.json"
    meta = json.loads(meta_path.read_text())
    frame_count = int(meta.get("frame_count", 6))
    durations = list(meta.get("frame_durations_ms") or [])
    if len(durations) != frame_count:
        print(f"error: frame_durations_ms has {len(durations)} entries but " +
              f"frame_count is {frame_count}; pipeline-meta.json mismatch")
        sys.exit(2)

    img = Image.open(src_path).convert("RGBA")
    sw, sh = img.size

    # 2 rows x 3 cols layout.
    cols, rows = 3, 2
    cell_w, cell_h = sw // cols, sh // rows

    frames = []
    for i in range(rows * cols):
        row = i // cols
        col = i % cols
        box = (col * cell_w, row * cell_h,
               (col + 1) * cell_w, (row + 1) * cell_h)
        cell = img.crop(box)
        cell = threshold_to_alpha(cell)
        frame_path = here / f"frame_{i+1}.png"
        cell.save(frame_path)
        frames.append(cell)
        print(f"wrote {frame_path.name}  {cell.size}  ({durations[i]}ms)")

    # Horizontal 1xN sheet for in-game atlas use.
    sheet_h = cell_h
    sheet_w = cell_w * len(frames)
    sheet = Image.new("RGBA", (sheet_w, sheet_h), (0, 0, 0, 0))
    for i, f in enumerate(frames):
        sheet.paste(f, (i * cell_w, 0), f)
    sheet_path = here / "sheet-transparent.png"
    sheet.save(sheet_path)
    print(f"wrote {sheet_path.name}  {sheet.size}")

    # Preview GIF with per-frame durations. GIF transparency is finicky;
    # threshold each frame's alpha to 1-bit at 128 so the bg color
    # (transparent pixel index 0) keys cleanly.
    gif_frames = []
    for f in frames:
        px = f.load()
        out = Image.new("RGBA", f.size, (0, 0, 0, 0))
        op = out.load()
        for y in range(f.size[1]):
            for x in range(f.size[0]):
                r, g, b, a = px[x, y]
                op[x, y] = (r, g, b, 255) if a >= 128 else (0, 0, 0, 0)
        gif_frames.append(out)
    gif_path = here / "animation.gif"
    gif_frames[0].save(
        gif_path,
        save_all=True,
        append_images=gif_frames[1:],
        duration=durations,
        loop=0,
        disposal=2,
        transparency=0,
    )
    total_ms = sum(durations)
    print(f"wrote {gif_path.name}  ({len(gif_frames)} frames, {total_ms}ms cycle)")


if __name__ == "__main__":
    main()
