#!/usr/bin/env python3
"""
Slice a 2-row x 3-col sprite-sheet generated by ChatGPT Image into 6
per-frame PNGs, assemble a horizontal sheet-transparent.png, and bake
an animation.gif with PER-FRAME durations read from
pipeline-meta.json's frame_durations_ms array.

Why this differs from wefty-fall/slice.py: the spin-hit cycle has
intentionally non-uniform timing (snappy 40ms at impact, longer at
anticipation/recovery). A single fps doesn't capture that, so we
honor the per-frame durations baked into the meta file.

Usage:
    python3 slice.py source-sheet.png

Inputs:
    source-sheet.png — raw 2x3 grid from ChatGPT.
    pipeline-meta.json — must contain frame_durations_ms: [...] with
        len == frame_count (6 here).

Outputs:
    frame_1.png .. frame_6.png — individual frames, transparent bg.
    sheet-transparent.png      — horizontal 1x6 sheet for in-game atlas.
    animation.gif              — 6 frames with per-panel durations.
"""
import sys
import json
import shutil
import subprocess
from pathlib import Path
from PIL import Image

# Pixels darker than this in all 3 channels are treated as background.
# Tuned for ChatGPT's solid-black canvas around the character.
BG_THRESHOLD = 24


def threshold_to_alpha(img: Image.Image) -> Image.Image:
    """Return a copy of img with near-black pixels keyed to alpha 0."""
    img = img.convert("RGBA")
    px = img.load()
    w, h = img.size
    for y in range(h):
        for x in range(w):
            r, g, b, _ = px[x, y]
            if r < BG_THRESHOLD and g < BG_THRESHOLD and b < BG_THRESHOLD:
                px[x, y] = (0, 0, 0, 0)
    return img


def main():
    if len(sys.argv) < 2:
        print("usage: python3 slice.py <source-sheet.png>")
        sys.exit(2)
    src_path = Path(sys.argv[1])
    if not src_path.exists():
        print(f"error: {src_path} not found")
        sys.exit(2)

    here = Path(__file__).parent.resolve()
    meta_path = here / "pipeline-meta.json"
    meta = json.loads(meta_path.read_text())
    frame_count = int(meta.get("frame_count", 6))
    durations = list(meta.get("frame_durations_ms") or [])
    if len(durations) != frame_count:
        print(f"error: frame_durations_ms has {len(durations)} entries but " +
              f"frame_count is {frame_count}; pipeline-meta.json mismatch")
        sys.exit(2)

    img = Image.open(src_path).convert("RGBA")
    sw, sh = img.size

    # 2 rows x 3 cols layout.
    cols, rows = 3, 2
    cell_w, cell_h = sw // cols, sh // rows

    frames = []
    for i in range(rows * cols):
        row = i // cols
        col = i % cols
        box = (col * cell_w, row * cell_h,
               (col + 1) * cell_w, (row + 1) * cell_h)
        cell = img.crop(box)
        cell = threshold_to_alpha(cell)
        frame_path = here / f"frame_{i+1}.png"
        cell.save(frame_path)
        frames.append(cell)
        print(f"wrote {frame_path.name}  {cell.size}  ({durations[i]}ms)")

    # Horizontal 1xN sheet for in-game atlas use.
    sheet_h = cell_h
    sheet_w = cell_w * len(frames)
    sheet = Image.new("RGBA", (sheet_w, sheet_h), (0, 0, 0, 0))
    for i, f in enumerate(frames):
        sheet.paste(f, (i * cell_w, 0), f)
    sheet_path = here / "sheet-transparent.png"
    sheet.save(sheet_path)
    print(f"wrote {sheet_path.name}  {sheet.size}")

    # Preview GIF with per-frame durations. GIF transparency requires
    # the transparent palette index to actually map to "ignore this
    # pixel" — Pillow's auto-quantize doesn't guarantee that. The
    # reliable recipe:
    #   1. Threshold each frame's alpha to 1-bit (>= 128 keeps RGB,
    #      < 128 becomes a sentinel color).
    #   2. Composite onto a sentinel-color RGB background so the
    #      formerly-transparent pixels now ARE that color.
    #   3. Quantize using a pre-built palette image where index 0 is
    #      the sentinel — Image.quantize(palette=) snaps each
    #      sentinel pixel to index 0.
    #   4. Save with transparency=0. Renderers see "index 0 is
    #      transparent" and skip those pixels cleanly.
    SENTINEL = (255, 0, 255)  # magenta; intentionally outside Wefty palette
    palette_data = list(SENTINEL) + [0, 0, 0] * 255
    pal_img = Image.new("P", (1, 1))
    pal_img.putpalette(palette_data)

    gif_frames = []
    for f in frames:
        rgba = f.convert("RGBA")
        # Threshold alpha
        alpha = rgba.split()[3].point(lambda a: 255 if a >= 128 else 0)
        bg = Image.new("RGB", rgba.size, SENTINEL)
        bg.paste(rgba, mask=alpha)
        # Quantize to a palette where index 0 is reserved for SENTINEL.
        # Use ADAPTIVE for the rest of the palette so character colors
        # don't get crushed.
        p = bg.quantize(colors=255, method=Image.Quantize.MEDIANCUT)
        # `quantize` produced its own adaptive palette indexed 0..254.
        # We need to remap so SENTINEL lives at index 0. Easiest: build
        # a new image with our palette + transparent index, then use
        # quantize again with the explicit pal_img.
        # Better: skip the auto-quantize — quantize directly against
        # pal_img after merging an adaptive palette.
        adaptive = bg.quantize(colors=255, method=Image.Quantize.MEDIANCUT)
        adaptive_palette = adaptive.getpalette()[:255 * 3]
        # Final palette: index 0 = SENTINEL, indices 1..255 = adaptive
        final_palette = list(SENTINEL) + adaptive_palette
        final_pal_img = Image.new("P", (1, 1))
        final_pal_img.putpalette(final_palette)
        p_final = bg.quantize(palette=final_pal_img, dither=Image.Dither.NONE)
        # Pillow's top-level transparency=/disposal= kwargs only stick to
        # frame 0 in save_all mode; subsequent frames need it baked into
        # their info dict or the renderer paints the sentinel opaque
        # (= flicker every other frame).
        p_final.info["transparency"] = 0
        p_final.info["disposal"] = 2
        gif_frames.append(p_final)

    gif_path = here / "animation.gif"
    gif_frames[0].save(
        gif_path,
        save_all=True,
        append_images=gif_frames[1:],
        duration=durations,
        loop=0,
        disposal=2,
        transparency=0,
        optimize=False,
    )
    total_ms = sum(durations)
    print(f"wrote {gif_path.name}  ({len(gif_frames)} frames, {total_ms}ms cycle)")

    # Pillow writes full-frame disposal=2 GIFs that flicker in browsers
    # (the disposal step briefly paints palette index 0 = sentinel
    # magenta as opaque between frames). gifsicle's optimizer rebuilds
    # the GIF as delta frames with proper transparent restore, killing
    # the flicker. Skipped silently if gifsicle isn't installed.
    if shutil.which("gifsicle"):
        subprocess.run(
            ["gifsicle", "-O3", "--careful", str(gif_path), "-o", str(gif_path)],
            check=True,
        )
        print(f"optimized {gif_path.name} via gifsicle")
    else:
        print("warning: gifsicle not found — GIF may flicker in browsers. " +
              "Install with: apt-get install gifsicle")


if __name__ == "__main__":
    main()
