#!/usr/bin/env python3
"""
Slice a 2-row × 3-col sprite-sheet generated by ChatGPT Image (or
gen_codex.mjs) into 6 per-frame PNGs, assemble a horizontal
sheet-transparent.png, and bake an animation.gif with PER-FRAME
durations read from pipeline-meta.json's frames[].duration_ms.

Usage:
    python3 slice.py source-sheet.png

Inputs:
    source-sheet.png — raw 2x3 grid from the painterly generator.
    manifest.json — must contain frames[] with duration_ms each.

Outputs:
    frame_1.png .. frame_6.png — individual frames, transparent bg.
    sheet-transparent.png      — horizontal 1x6 sheet for in-game atlas.
    animation.gif              — N frames with per-panel durations.

GIF transparency fix (vs. wefty-fall / wefty-spin-hit slicers):
    PIL's adaptive quantizer assigns palette slots in colour-frequency
    order. If we hand it RGB+A and tell GIF "transparency=0", the
    palette index that ends up at slot 0 is whatever PIL picked first,
    NOT the transparent region — so renderers either see wrong-colour
    pixels keyed transparent, or fall back to drawing palette colours
    where the supposed-transparent region was.

    Fix: composite each frame's transparent pixels onto a SENTINEL
    RGB (pure magenta 255,0,255 — guaranteed not to appear in painterly
    Wefty output), quantize the result to 255 colours, append the
    sentinel as palette index 255, and tell GIF "transparency=255".
    Now there is no ambiguity: index 255 is, and always will be, the
    transparent slot.
"""
import sys
import json
from pathlib import Path
from PIL import Image

# Pixels darker than this in all 3 channels are treated as background.
# Tuned for ChatGPT's solid-black canvas around the character.
BG_THRESHOLD = 24

# Pure magenta — used as the GIF transparency sentinel because painterly
# Wefty's palette is purples/pinks/mints/peaches; pure (255,0,255) is
# absent from the rendered character.
SENTINEL_RGB = (255, 0, 255)
SENTINEL_INDEX = 255  # last slot of the 256-colour GIF palette


def threshold_to_alpha(img: Image.Image) -> Image.Image:
    """Return a copy of img with near-black pixels keyed to alpha 0."""
    img = img.convert("RGBA")
    px = img.load()
    w, h = img.size
    for y in range(h):
        for x in range(w):
            r, g, b, _ = px[x, y]
            if r < BG_THRESHOLD and g < BG_THRESHOLD and b < BG_THRESHOLD:
                px[x, y] = (0, 0, 0, 0)
    return img


def to_gif_frame(rgba: Image.Image) -> Image.Image:
    """
    Convert an RGBA frame to a paletted GIF frame with the transparent
    region pinned to palette index SENTINEL_INDEX. See module docstring
    for why this avoids the PIL quantizer's transparent-index bug.
    """
    # 1. Paint the transparent region with the sentinel colour so it
    #    survives quantization as a single, identifiable colour cluster.
    sentinel_bg = Image.new("RGB", rgba.size, SENTINEL_RGB)
    rgb = rgba.convert("RGB")
    alpha = rgba.split()[3]
    composited = Image.composite(rgb, sentinel_bg, alpha)

    # 2. Quantize to 255 colours, leaving palette slot SENTINEL_INDEX
    #    open for our sentinel.
    paletted = composited.quantize(colors=255, method=Image.MEDIANCUT)

    # 3. Inject the sentinel at SENTINEL_INDEX.
    palette = list(paletted.getpalette() or [])
    while len(palette) < 256 * 3:
        palette.append(0)
    palette[SENTINEL_INDEX * 3:SENTINEL_INDEX * 3 + 3] = list(SENTINEL_RGB)
    paletted.putpalette(palette)

    # 4. Write SENTINEL_INDEX into every pixel that was transparent in
    #    the source. Mask = 255 where we want to paste the sentinel.
    transparent_mask = alpha.point(lambda a: 255 if a < 128 else 0)
    paletted.paste(SENTINEL_INDEX, mask=transparent_mask)

    return paletted


def main():
    if len(sys.argv) < 2:
        print("usage: python3 slice.py <source-sheet.png>")
        sys.exit(2)
    src_path = Path(sys.argv[1])
    if not src_path.exists():
        print(f"error: {src_path} not found")
        sys.exit(2)

    here = Path(__file__).parent.resolve()
    manifest_path = here / "manifest.json"
    manifest = json.loads(manifest_path.read_text())
    frame_count = int(manifest.get("frame_count", 6))
    frames_block = manifest.get("prompts", {}).get("frames") or manifest.get("frames")
    if not frames_block:
        print("error: manifest has no frames block (looked at prompts.frames and frames)")
        sys.exit(2)
    durations = [int(f["duration_ms"]) for f in frames_block]
    if len(durations) != frame_count:
        print(f"error: manifest has {len(durations)} frame durations but "
              f"frame_count is {frame_count}")
        sys.exit(2)

    img = Image.open(src_path).convert("RGBA")
    sw, sh = img.size

    # 2 rows x 3 cols layout (row-major).
    cols, rows = 3, 2
    cell_w, cell_h = sw // cols, sh // rows

    rgba_frames = []
    for i in range(rows * cols):
        row = i // cols
        col = i % cols
        box = (col * cell_w, row * cell_h,
               (col + 1) * cell_w, (row + 1) * cell_h)
        cell = img.crop(box)
        cell = threshold_to_alpha(cell)
        frame_path = here / f"frame_{i + 1}.png"
        cell.save(frame_path)
        rgba_frames.append(cell)
        print(f"wrote {frame_path.name}  {cell.size}  ({durations[i]}ms)")

    # Horizontal 1xN sheet for in-game atlas.
    sheet_w = cell_w * len(rgba_frames)
    sheet = Image.new("RGBA", (sheet_w, cell_h), (0, 0, 0, 0))
    for i, f in enumerate(rgba_frames):
        sheet.paste(f, (i * cell_w, 0), f)
    sheet_path = here / "sheet-transparent.png"
    sheet.save(sheet_path)
    print(f"wrote {sheet_path.name}  {sheet.size}")

    # Animation GIF — sentinel-anchored transparency.
    gif_frames = [to_gif_frame(f) for f in rgba_frames]
    gif_path = here / "animation.gif"
    gif_frames[0].save(
        gif_path,
        save_all=True,
        append_images=gif_frames[1:],
        duration=durations,
        loop=0 if manifest.get("loop", False) else 1,
        disposal=2,
        transparency=SENTINEL_INDEX,
        optimize=False,
    )
    total_ms = sum(durations)
    print(f"wrote {gif_path.name}  ({len(gif_frames)} frames, {total_ms}ms cycle)")


if __name__ == "__main__":
    main()
